### PR TITLE
Inline attachment fixes

### PR DESCRIPTION
**Pull request by Graham--M**
This pull request fixes several problems with the inline attachment css.

**Fix 1: Video attachment details**
When a video attachment is expanded, the thumbnail is hidden but the attachment wrapper still has it's height set leaving a large gap between the video player and the attachment details. This is fixed by setting the height back to `inherit` when the attachment is expanded.

**Fix 2: Overflowing attachments**
Images and videos overflow the post container if they are bigger than the maximum post width for the current window size in internet explorer 11 and firefox. This is because the `max-width` on the attachment is set to a percentage and the attachment is contained in several `inline-block` elements.

In the css 2.1 spec, if a percentage based measurement depends on the width of a parent element, and that parent element's width depends on the width of it's children, the layout behavior is undefined. Chrome seems to do extra calculations so the max width is set correctly but other browsers set the max width to the unrestrained size of the image/video.

I've set a max width on the expanded post container and the floated `ul.post-attachments` so that the max width is no longer dependent on the child elements and the images/videos scale properly when they are bigger than the post width.

~~One issue with this fix is that the max-width constrains the content width rather than the content width + padding so the ul overflows to the right because of the `padding-left` it has in a post reply. The workaround for this is either to increase the `padding-right` of the `li.post-attachment` (which results in a larger padding for attachments which are smaller than the post content width) or to set the max-width of the ul in replies to 99% (which I have done) so that the image always has a little padding to the right.~~

**Fix 3: Audio attachment sizing and aspect ratio**
The audio attachment animation was causing the attachment to overflow the `ul.post-attachments` resulting in scrollbars appearing and glitching as the animation overflowed. The fix for this is to set the `figure` element to hide overflowing (as the extra space in the svg leaves a gap) and to make sure the wrapper and figure have a big enough content width. The content width wasn't big enough because the `::after` element is absolutely positioned (taking it out of the normal width calculations) so padding is used to make the width wide enough to stop the vinyl from overflowing.

A second issue is that chrome was resizing the height and width down for the cover art which made it smaller than specified and sometimes resulted in an incorrect aspect ratio. Again this is caused undefined behavior for the percentage based padding in an `inline-block` so I've changed this to a fixed padding so that the behavior is consistent between browsers.

I've also tweaked the attachment name so that it centers correctly with the other details and added padding to the audio player so that the time cursor in firefox isn't clipped.

**Notes**
* ~~Internet explorer doesn't support the animation css ([link](https://dev.windows.com/en-us/microsoft-edge/platform/status/csstransitionsanimationsforsvgelements)). I might try use ie specific rules or a js shim to add support.~~
* I've tested these fixes to the best of my ability but internet explorer was locking up with the javascript usage on the beta site so some issues could crop up there. Let me know.
* You changed the css of attachments slightly (I think to try solve the same problem) so I haven't merged commits made after these fixes.

### CODE REVIEW

**Comment by Graham--M** [comment]
I've just realized that you can use `calc` with a fallback rule. I'll do an update. Can you let me know if the multi-attachments are supposed to have a horizontal scroll because I can put that back in if needed by turning off white-space wrapping.

**Comment by Graham--M** [comment]
Oh hell. The vinyl disk offset far enough. I need to change that.

**Comment by Graham--M** [comment]
Ok that's better; now the vinyl svg matches up with the old css. I also got rid of the bottom margin on the file name because there was a gap. I did notice that this new offset overflows (and is hidden) for small screens so a future improvement would either be to (in `responsive.css`) jump to smaller dimensions or reduce the offset padding to what I had in the previous commit.

What I said about fixing IE's svg animation earlier doesn't have an ideal solution because the JavaScript libraries either are CPU intensive or use flash.

**Comment by Graham--M** [comment]
So I was wrong about the reason why the animation wasn't working in IE11. Inline svg refers to the svg html tag rather than an external image.

The animation rule was probably just too sophisticated for it because I got the animation working with a smaller rule. I'll commit the change after I've finished fixing the infinity logo in the svg because that isn't showing up in IE either.

**Comment by Graham--M** [comment]
There we go. I've changed the animation rule to the same form as Font Awesome uses so the animation now works with IE11.

The Infinity logo on the svg wasn't showing up in IE either. I'm not sure of the exact cause. Anyway it worked after I copied the unlinked symbol in inkscape to another file and back, so now it should all work in IE too.

Sorry if this pr is getting a bit monolithic.

**Comment by jaw-sh** [comment]
@Graham--M Would you mind resolving conflicts?

**Comment by Graham--M** [comment]
I'll do that (although I'm going to setup a VM since I can't test effectively on odili or the beta site). Can you tell me how multi attachments work on small screens? Should they wrap or do they have a scroll bar?

**Comment by Graham--M** [comment]
The VM was useless because I ran into [this issue](https://github.com/infinity-next/infinity-next/issues/224), so I had to test these with a modified style sheet in place of the site served one.

**Comment by Graham--M** [comment]
OK. I got my VM working and serving attachments so I've tested the changes in a full Infinity Next install and they are working as intended.

My only complaint is that weird aspect ratios on audio attachment cover art can clip or completely cover the vinyl animation but this is the same behavior with as the existing CSS and almost all cover art has an aspect ratio close to 1:1 anyway.

**Pull request merged**
