### PR TITLE
[WIP] Order threads by last stickied

### LINKED ISSUE #293: Ability for BOs to sort stickied threads?
There doesn't seem to be a way to order the position of stickied threads. As a BO it's quite annoying.

### PR DESCRIPTION
**Pull request by GarbageHamburger**
Fixes #293.

### CODE REVIEW

**Comment by GarbageHamburger** [comment]
It seems like it's implementation defined, as mentioned in 50f0cc2.
@jaw-sh Are you able to test this PR?

**Comment by GarbageHamburger** [comment]
After talking it over a bit on the Laravel IRC, it seems like there's another approach: We can use `->orderBy('stickied_at', 'desc nulls last')` here, but this might not be implemented by all database vendors. In particular, PostgreSQL implements this, but [MySQL has an undocumented custom syntax](https://stackoverflow.com/a/8174026). This approach might be better, and shouldn't affect performance in any noticeable way.

**Comment by jaw-sh** [comment]
The primary databse interest is going to be PgSQL, make sure whatever you're doing works with that.

**Comment by jaw-sh** [comment]
Though I don't see the point of this. Neither 4chan nor 8chan ever presented stickies by the order of the sticky. They presented them in the order of the last post.

**Comment by GarbageHamburger** [comment]
Boards might want to have their stickies sorted in a certain way. A board might want to have a locked sticky with information at the top of the board.
>Neither 4chan nor 8chan ever presented stickies by the order of the sticky. They presented them in the order of the last post.
That's true, but somehow boards like 8/tech/ always preserved their sort order, regardless of bumps.

**Pull request merged**
