### PR TITLE
Updated Nginx Config

### PR DESCRIPTION
**Pull request by rajlaksh**
Updated Nginx Config

https://github.com/rajlaksh/infinity-next/wiki/WebServer-Configuration

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
We're already discussing this, see https://github.com/infinity-next/infinity-next/commit/07e45e8f8bb8617a23ac7b3a7f7cc3804f8b790b and https://github.com/infinity-next/infinity-next/tree/proposed-nginx-config

So far as I can tell your proposal has no benefits over mine.

**Comment by rajlaksh** [comment]
`fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;` cause error

**Comment by ctrlcctrlv** [comment]
Maybe on your system, try my *whole* config; it works if you follow the instructions.

**Comment by rajlaksh** [comment]
Yeah, OS maybe cause it. i get 403 is there is no index.html or index.php file.

`set $webroot /srv/http/infinity-next;` don't need

**Comment by jaw-sh** [comment]
@rajlaksh Can you try mine? I'm only including relevant parts. This is missing passing things through the FastCGI daemon.

```
        root /var/www/infinitydev.org/next;
        index index.php;
 
        location /attachments {
                internal;
                alias /var/www/infinitydev.org/next/storage/app/attachments;
        }
 
        location / {
                try_files /public/$uri /public/$uri/ /public/index.php$is_args$args;
        }
```

The important bit is this.

```
        location /attachments {
                internal;
                alias /var/www/infinitydev.org/next/storage/app/attachments;
        }
 ```

This catches the `X-Accel-Redirect` header and will send the file directly.

Ultimately the webserver configuration is the responsibility of the webserver manager. I can't provide a config for every computer.

**Comment by ctrlcctrlv** [comment]
What's more important is the MIME issue @rajlaksh . I was even considering writing an nginx module to add a `mime_uri` directive (more than considering, I actually have a sort-of working one on my disk right now, but it leaks memory...such is life in C).

`set`, etcetera, are just tertiary issues.

**Comment by rajlaksh** [comment]
@jaw-sh  /public/index.php$is_args$args;? i think query_string

**Comment by ctrlcctrlv** [comment]
>  /public/index.php$is_args$args;? i think query_string

# TERTIARY ISSUE

**Comment by rajlaksh** [comment]
@ctrlcctrlv  no issue in my Nginx.

**Comment by ctrlcctrlv** [comment]
@rajlaksh Open an image in a new tab; it downloads as `application/octet-stream`. That's wrong behavior.

**Comment by rajlaksh** [comment]
I can't test that.

**Comment by ctrlcctrlv** [comment]
Why not? Are you saying you wrote and PR'd an nginx config without testing it?

**Comment by jaw-sh** [comment]
@rajlaksh rajlakash, he is saying that your problem is irrelevant to the scope of this. Please fix it on your own server. We can't accept it. Our ''primary concern'' right now is routing requests so that PHP doesn't have to serve up static content.

**Comment by rajlaksh** [comment]
I use Laravel and I know how routing works :+1:

**Comment by rajlaksh** [comment]
In My 4chan like in Laravel it show Images in Browser :smile:

**Comment by rajlaksh** [comment]
@ctrlcctrlv try Mine config it will work too.

**Comment by ctrlcctrlv** [comment]
>Oct 11 14:38:41 hachi nginx[1156]: 2015/10/11 14:38:41 [emerg] 1156#0: unknown "static" variable

You didn't test this at all.

**Comment by rajlaksh** [comment]
@ctrlcctrlv  i should i've if I was Able to create a Thread.

**Comment by ctrlcctrlv** [comment]
Whatever dude. Here's a few simple questions, and this time don't side-step them:

https://raw.githubusercontent.com/rajlaksh/infinity-next/4541a1f1e4262d9008470ff8a820a5ad37224197/contrib/configs/nginx/infinity-next

1. _Where is `$static` declared?_
2. What is the purpose of the extra paranthesis on line 31?

Just admit you didn't test this and took a big shit in our inbox. The nginx config preprocessor isn't wrong, you are.

If I was @jaw-sh I'd block you from commenting and opening PR's.

**Comment by rajlaksh** [comment]
@jaw-sh  helped me to fix it. I tested it and it works.

**Comment by ctrlcctrlv** [comment]
Your cache problem caused by using a non-existent cache method has absolutely no relation to the nginx config problems.

facepalm

**Comment by rajlaksh** [comment]
Default is File Cache what is wrong?

**Comment by ctrlcctrlv** [comment]
Naruto sucks.

**Pull request closed without merging**
