### PR TITLE
CSS Validation

### PR DESCRIPTION
**Pull request by interjection**
If you notice anything wrong and don't want to merge this yet I can probably fix it up when I get some time, but I won't have a dev environment this week.

Have a bunch of test cases as well but couldn't figure out how to integrate into tests within a few minutes so I gave up. Maybe another time.

Caveats: `config/css.php`
You'll need to expand the mime types allowed, I would not recommend allowing svg
The CSS filter rule is problematic for a number of reasons, so it's commented out for now.

Lemme know if I fucked up.

### CODE REVIEW

**Comment by jaw-sh** [comment]
This PR looks utterly flawless. I'll test it out as soon as I get a chance.

Never pulled in a PR before, so hopefully I'm not supposed to test before merging, haha.

**Comment by jaw-sh** [comment]
The three things I've identified are:

1) The Word Filter config option throws a very bizarre array to string conversion error when I try to save a board's config now. I'm still tracking this down.

2) I see an option for an `@import` blacklist, but not a whitelist.

3) Missing language, which isn't really a problem.

**Comment by interjection** [comment]
>1) The Word Filter config option throws a very bizarre array to string conversion error when I try to save a board's config now. I'm still tracking this down.

It did that before when anything failed validation. I tried tracking it down with bisect like two months ago but I think it's the template itself you added with the way you're returning arrays. I tried reading up on the new 5.2 array stuff that they improved, you should look into that. I think that was the correct path for upgrading that particular part to 5.2 onward.

>2) I see an option for an `@import` blacklist, but not a whitelist.

I took the idea from how Fred originally implemented it, but did it correctly this time (without regular expressions.)

The idea is that it's a blanket whitelist for assets/imports, and only a blacklist for `@import` directives. Say, if you have a particular file hosting site that you can upload javascript or any file you want, but only want to allow images from that domain. Then you blacklist that site from `@import`.

>3) Missing language, which isn't really a problem.

I wanted that and tests. Clunky, my apologies if you see an obvious way it could be done better.

**Comment by jaw-sh** [comment]
Can you not include images in the remote CSS and completely defeat the asset URL filter?

**Comment by interjection** [comment]
>Can you not include images in the remote CSS and completely defeat the asset URL filter?

Hence the blacklist. For example: if you whitelisted googleapis we're assuming the attacker can't upload/modify the assets/imports to be malicious. If you whitelisted mixtape or another pomf clone, we cannot assume that an import directive can be safe.

Therefore hosts that allow uploading of arbitrary files beyond images should be blacklisted.

That was the idea, anyways.

**Comment by jaw-sh** [comment]
Yeah but that's a very incomplete tactic. I can literally setup a website and host my own CSS and then get around any blacklist. From the way this looks, I could also theoretically set up an infinite amount of subdomains on one URL and get around any number of blacklists.

**Comment by interjection** [comment]
Whoops. That was an oversight. I must've been thinking of the version before I refactored and split it up into different functions.

You'd modify the AllowedImportUrl function to check if it's in the whitelist.

Sorry about that.

**Comment by interjection** [comment]
Hence why tests would've been good.

**Comment by jaw-sh** [comment]
Yeah no drama, I recently added a Content Origin Policy to the HTML as a lazy way of blackballing all foreign resources anyways :P

**Comment by interjection** [comment]
I pulled in https://github.com/stevenmaguire/laravel-middleware-csp for that, it was pretty configurable on a route basis.

If you want to make that small change to `isAllowedImportUrl` I'd appreciate it, otherwise I'll get around to it next week when I can sit down in front of my workstation.

**Pull request merged**
