### PR TITLE
fix nginx rewrite rules for attachments files and thumbnails to avoid rewrite cycles

### PR DESCRIPTION
**Pull request by zefredz**
Hello,

I've fixed the rules in the file because they were creating rewrite cycles when accessing files and thumbnails.

I hope this could help.

-- ZeFredz

### CODE REVIEW

**Comment by jaw-sh** [comment]
We have another config that works. I'd like you to look at it after I submit it to the repo.

**Comment by jaw-sh** [comment]
@zefredz Please let me know what you think about this.

https://github.com/infinity-next/infinity-next/wiki/Installation

**Comment by zefredz** [comment]
OK, I'll try this as soon as possible.

Thanks.

**Comment by zefredz** [comment]
It works perfectly, thanks :)

**Pull request closed without merging**
